# Production Docker Compose Configuration
# Use this to test the production build locally
# Run with: docker-compose -f docker-compose.prod.yml up

services:
  # ============================================
  # Next.js Application (Production Mode)
  # ============================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: donor-crm-prod-app
    ports:
      - "3000:3000"
    environment:
      # Supabase Connection
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-https://asclamyhgsbgixleplte.supabase.co}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      # Node environment
      - NODE_ENV=production
    networks:
      - crm-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    # No volumes - uses the built standalone server

  # ============================================
  # PostgreSQL Database
  # ============================================
  postgres:
    image: postgres:15-alpine
    container_name: donor-crm-prod-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=donor_crm
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - crm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================
  # Redis
  # ============================================
  redis:
    image: redis:7-alpine
    container_name: donor-crm-prod-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-prod-data:/data
    networks:
      - crm-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# ============================================
# Networks
# ============================================
networks:
  crm-network:
    driver: bridge

# ============================================
# Volumes
# ============================================
volumes:
  postgres-prod-data:
    driver: local
  redis-prod-data:
    driver: local
