# Local Production Docker Compose Configuration
# Runs the app in production mode, connecting to remote Supabase
# Usage: docker-compose -f docker-compose.local-prod.yml --env-file .env.docker up --build
#
# IMPORTANT: Create .env.docker file with your Supabase credentials
# See .env.docker.example for template

services:
  # ============================================
  # Next.js Application (Production Mode)
  # ============================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: donor-crm-local-prod
    ports:
      - "3000:3000"
    environment:
      # Supabase Connection (loaded from .env.docker)
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Node environment
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - crm-network

# ============================================
# Networks
# ============================================
networks:
  crm-network:
    driver: bridge
