# Local Production Docker Compose Configuration
# Runs the app in production mode, connecting to local Supabase
# Usage: docker-compose -f docker-compose.local-prod.yml up --build

services:
  # ============================================
  # Next.js Application (Production Mode)
  # ============================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=https://flqgkpytrqpkqmedmtuf.supabase.co
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscWdrcHl0cnFwa3FtZWRtdHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTU0NDgsImV4cCI6MjA3NjI3MTQ0OH0.tK3fERyqheOxtFSICkHuU0aVLzg9AwXgnECAPElgBXg
    container_name: donor-crm-local-prod
    ports:
      - "3000:3000"
    environment:
      # Supabase Connection (Remote Cloud - No local Supabase needed!)
      # Both browser and server connect directly to Supabase cloud via HTTPS
      - NEXT_PUBLIC_SUPABASE_URL=https://flqgkpytrqpkqmedmtuf.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscWdrcHl0cnFwa3FtZWRtdHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTU0NDgsImV4cCI6MjA3NjI3MTQ0OH0.tK3fERyqheOxtFSICkHuU0aVLzg9AwXgnECAPElgBXg
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscWdrcHl0cnFwa3FtZWRtdHVmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDY5NTQ0OCwiZXhwIjoyMDc2MjcxNDQ4fQ.jatPHfLaKxVvZnnNI5QycHnCx0gX6gFIdiBVybgPbFU
      # Node environment
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - crm-network

# ============================================
# Networks
# ============================================
networks:
  crm-network:
    driver: bridge
